"""Create warp_instances table

Revision ID: b1da196f1fb4
Revises: 
Create Date: 2025-08-03 13:24:32.210611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1da196f1fb4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warp_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('socks5_port', sa.Integer(), nullable=False),
    sa.Column('is_managed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('socks5_port')
    )
    op.create_index(op.f('ix_warp_instances_id'), 'warp_instances', ['id'], unique=False)
    op.create_index(op.f('ix_warp_instances_name'), 'warp_instances', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warp_instances_name'), table_name='warp_instances')
    op.drop_index(op.f('ix_warp_instances_id'), table_name='warp_instances')
    op.drop_table('warp_instances')
    # ### end Alembic commands ###
