warp_instances:
  - name: "warp-instance-1"
    socks5_port: 9091
    http_proxy_port: 8081
  - name: "warp-instance-2"
    socks5_port: 9092
    http_proxy_port: 8082

health_checker:
  timeout_seconds: 10
  check_urls:
    - "https://www.cloudflare.com/cdn-cgi/trace"
    - "https://ip.gs" # 备用 URL