name: Docker Publish

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: crisrain/warppool

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push frontend Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: ghcr.io/${{ env.IMAGE_NAME }}/frontend:latest

    - name: Build and push controller-app Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./controller-app
        file: ./controller-app/Dockerfile
        push: true
        tags: ghcr.io/${{ env.IMAGE_NAME }}/controller-app:latest

    - name: Build and push warp-instance Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./warp-instance
        file: ./warp-instance/Dockerfile
        push: true
        tags: ghcr.io/${{ env.IMAGE_NAME }}/warp-instance:latest